baseURL: https://www.quantumjosh.me/

languageCode: en-us
title: "Quantum Josh (site under construction)"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

enableEmoji: true

params:
  gitRepo: https://github.com/jmgloria07/quantumjosh.me
  gitBranch: master

  background: "images/background.jpg"

  logo:
    main: images/logo/main-logo.png
    inverted: images/logo/main-logo.png
    favicon: images/logo/main-logo.png
  enableBlogPost: false
  enableTOC: true
  newsletter:
    enable: false
  footer:
    disclaimer:
      enable: true